# Automatically increments patch version if push doesn't contain a new version
name: Patch Version

on:
  push:
    branches: ['master']

jobs:
  patch:
    name: Patch Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Find Tag
        id: tagger
        run: echo "TAG_NAME=$(git describe --tags HEAD)" >> $GITHUB_OUTPUT
      - name: Show Tag
        run: echo ${{ steps.tagger.outputs.TAG_NAME }}
      - name: Conditional Termination
        if: ${{ contains(steps.tagger.outputs.TAG_NAME, '-') }}
        run: exit 1
      - name: Set git credentials
        run: |
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
      - name: New patch version
        run: npm version patch
      - name: Git Push
        run: git push --follow-tags
