name: Update Patch Version

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Update Patch Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIAL}}
      - name: Update patch version
        run: npm version patch
      - name: Push tag
        run: git push
